#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT

set -e -o pipefail

# shellcheck disable=SC1091
. "$(dirname "$0")/../sub-scripts/all.sh"

name=$1
if [ -z "${name}" ]; then
    warn_it "Use it like this: 'branch 42', where 42 is the name of the branch and GitHub issue number"
    exit 1
fi

# shellcheck disable=SC2154
title_it "Checking out the origin/${master} branch"
# shellcheck disable=SC2154
bash_it "${GIT_BIN}" checkout "${master}"

# shellcheck disable=SC2154
"${base}/pull"

title_it "Showing the current status"
bash_it "${GIT_BIN}" status

title_it "Checking out the origin/${name} branch"
bash_it "${GIT_BIN}" checkout -b "${name}"

while true; do
    title_it "Pushing to the origin/${name} branch"
    bash_it "${GIT_BIN}" push origin "${name}" && break
    if [ -n "${GITTED_TESTING}" ]; then
        exit 1
    fi
done

title_it "Setting the upstream of the origin/${name} branch"
bash_it "${GIT_BIN}" branch "--set-upstream-to=origin/${name}" "${name}"
