#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT

set -e -o pipefail

base=$(realpath "$(dirname "$0")/..")

"${base}/fn/fail-if-not-git.sh"

if [ -e .git/modules ]; then
  while true; do
    git submodule update --remote && break
    if [ -n "${GITTED_TESTING}" ]; then
      exit 1
    fi
  done
fi

trap 'git stash apply' EXIT
git stash
while true; do
  git pull && break
done
trap - EXIT
git stash apply
