#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT

set -e -o pipefail

if [ -n "${GITTED_TESTING}" ]; then
    set -x
fi

if [ -n "${GITTED_VERBOSE}" ]; then
    set -x
fi

echo "Gitted 0.0.0 (any issues or ideas, submit to https://github.com/yegor256/gitted)"

function bash_it {
    printf '%q ' "$@" | /bin/bash -x
}

if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo "Oops, this is not a Git repository"
    exit 1
fi

if [ -z "${GIT_BIN}" ]; then
    GIT_BIN=git
fi

branch=$("${GIT_BIN}" symbolic-ref HEAD --short)
if [ -z "${branch}" ]; then
    echo "Something is wrong, the current branch was not detected"
    exit 1
fi
printf "\nCurrent branch is \e[1m%s\e[0m\n" "${branch}"

if ! "${GIT_BIN}" rev-parse --abbrev-ref --symbolic-full-name '@{u}' >/dev/null 2>&1; then
    printf "\nThe upstream is not configured for the '%s' branch, setting it to 'origin/%s'" "${branch}" "${branch}"
    bash_it "${GIT_BIN}" fetch
    bash_it "${GIT_BIN}" branch "--set-upstream-to=origin/${branch}" "${branch}"
fi

if [ -e .git/modules ]; then
    printf "\n\e[1mUpdating\e[0m a few submodules first...\n"
    while true; do
        bash_it "${GIT_BIN}" submodule update --remote && break
        if [ -n "${GITTED_TESTING}" ]; then
            exit 1
        fi
    done
fi

printf "\nStaging local changes (%d files)...\n" "$(${GIT_BIN} status --porcelain | wc -l)"
bash_it "${GIT_BIN}" add .

stashed=no
if ! git diff --quiet || ! git diff --cached --quiet; then
    trap "printf '\nApplying the changes back...\n' && bash_it \${GIT_BIN} stash apply" EXIT
    printf "\n\e[1mStashing\e[0m local changes (%d files)...\n" "$(${GIT_BIN} status --porcelain | wc -l)"
    bash_it "${GIT_BIN}" stash
    stashed=yes
fi

while true; do
    printf "\n\e[1mPulling\e[0m from %s...\n" "origin/${branch}"
    bash_it "${GIT_BIN}" pull origin "${branch}" && break
    if [ -n "${GITTED_TESTING}" ]; then
        exit 1
    fi
done
trap - EXIT
if [ "${stashed}" == 'yes' ]; then
    printf "\nTrying to \e[1mapply\e[0m the changes back...\n"
    bash_it "${GIT_BIN}" stash apply
fi

# Then, we should pull+merge from upstream...
