#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT

set -e -o pipefail

# shellcheck disable=SC1091
. "$(dirname "$0")/../sub-scripts/all.sh"

# shellcheck disable=SC2154
"${base}/pull" "$*"

if git status --porcelain | grep -q .; then
    # shellcheck disable=SC2154
    "${base}/commit" "$*"
else
    title_it "Nothing to commit, proceeding with push"
fi

branch=$(git symbolic-ref HEAD --short)

retry_it "Pushing to origin/${branch}" "bash_it ${GIT_BIN} push origin ${branch}"
